---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: ocowchun_ubuntu-14.04_ruby2
      box_url: https://s3-ap-northeast-1.amazonaws.com/achilles-warehouse/boxes/package.box     
      network:
      - ["private_network", {ip: "192.168.33.33"}]
      synced_folders: 
      - ["../shadow", "/opt/instance_data"]

suites:
  - name: default
    run_list: pita::default
    attributes:
      rackbox:
        ruby:
          versions: "2.0.0-p451"
          global_version: "2.0.0-p451"




