---
driver:
  name: ssh


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04


suites:
  - name: default
    run_list: pita::default
    attributes:
      # rackbox:
      #   ruby:
      #     versions: "2.0.0-p451"
      #     global_version: "2.0.0-p451"




