---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list: pita::default
    attributes:
      rackbox:
        ruby:
          versions: "2.0.0-p451"
          global_version: "2.0.0-p451"


